name: Get and commit GitHub stars
on: workflow_dispatch
jobs:
  stars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          
          cd $GITHUB_WORKSPACE
          git pull origin main
      - name: Get GitHub stars
        run: |
          curl https://api.github.com/users/hugginsio/starred -H "Accept: application/json" -s --output stars.json
      - name: Commit stars.json
        run: |
          git add stars.json
          git commit -m "Update stars.json ($(env TZ='America/Chicago' date -Im))" || echo "No changes to GitHub stars"
          git push origin main
