name: Get and commit GitHub stars
on: workflow_dispatch
jobs:
  stars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get GitHub stars
        run: |
          curl https://api.github.com/users/hugginsio/starred -H "Accept: application/json" -s --output stars.json
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit stars.json
        run: |
          git add stars.json
          git commit -m echo "Update stars.json ($(env TZ='America/Chicago' date -Im))" || echo "No changes to GitHub stars"
          git push origin main
